# Generated by Django 5.0.3 on 2024-03-15 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='name',
            new_name='field1',
        ),
        migrations.RenameField(
            model_name='mymodel',
            old_name='description',
            new_name='field2',
        ),
    ]
