# Generated by Django 5.0.3 on 2024-03-15 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_mymodel_field1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='field2',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='mymodel',
            old_name='field1',
            new_name='name',
        ),
    ]
